// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module runge_kutta_45_runge_kutta_45_Pipeline_last_axi_write_tt (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_T_BUS_AWVALID,
        m_axi_T_BUS_AWREADY,
        m_axi_T_BUS_AWADDR,
        m_axi_T_BUS_AWID,
        m_axi_T_BUS_AWLEN,
        m_axi_T_BUS_AWSIZE,
        m_axi_T_BUS_AWBURST,
        m_axi_T_BUS_AWLOCK,
        m_axi_T_BUS_AWCACHE,
        m_axi_T_BUS_AWPROT,
        m_axi_T_BUS_AWQOS,
        m_axi_T_BUS_AWREGION,
        m_axi_T_BUS_AWUSER,
        m_axi_T_BUS_WVALID,
        m_axi_T_BUS_WREADY,
        m_axi_T_BUS_WDATA,
        m_axi_T_BUS_WSTRB,
        m_axi_T_BUS_WLAST,
        m_axi_T_BUS_WID,
        m_axi_T_BUS_WUSER,
        m_axi_T_BUS_ARVALID,
        m_axi_T_BUS_ARREADY,
        m_axi_T_BUS_ARADDR,
        m_axi_T_BUS_ARID,
        m_axi_T_BUS_ARLEN,
        m_axi_T_BUS_ARSIZE,
        m_axi_T_BUS_ARBURST,
        m_axi_T_BUS_ARLOCK,
        m_axi_T_BUS_ARCACHE,
        m_axi_T_BUS_ARPROT,
        m_axi_T_BUS_ARQOS,
        m_axi_T_BUS_ARREGION,
        m_axi_T_BUS_ARUSER,
        m_axi_T_BUS_RVALID,
        m_axi_T_BUS_RREADY,
        m_axi_T_BUS_RDATA,
        m_axi_T_BUS_RLAST,
        m_axi_T_BUS_RID,
        m_axi_T_BUS_RFIFONUM,
        m_axi_T_BUS_RUSER,
        m_axi_T_BUS_RRESP,
        m_axi_T_BUS_BVALID,
        m_axi_T_BUS_BREADY,
        m_axi_T_BUS_BRESP,
        m_axi_T_BUS_BID,
        m_axi_T_BUS_BUSER,
        add405,
        tt_loc_V_address0,
        tt_loc_V_ce0,
        tt_loc_V_q0,
        tt,
        zext_ln257,
        trunc_ln14
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_T_BUS_AWVALID;
input   m_axi_T_BUS_AWREADY;
output  [63:0] m_axi_T_BUS_AWADDR;
output  [0:0] m_axi_T_BUS_AWID;
output  [31:0] m_axi_T_BUS_AWLEN;
output  [2:0] m_axi_T_BUS_AWSIZE;
output  [1:0] m_axi_T_BUS_AWBURST;
output  [1:0] m_axi_T_BUS_AWLOCK;
output  [3:0] m_axi_T_BUS_AWCACHE;
output  [2:0] m_axi_T_BUS_AWPROT;
output  [3:0] m_axi_T_BUS_AWQOS;
output  [3:0] m_axi_T_BUS_AWREGION;
output  [0:0] m_axi_T_BUS_AWUSER;
output   m_axi_T_BUS_WVALID;
input   m_axi_T_BUS_WREADY;
output  [127:0] m_axi_T_BUS_WDATA;
output  [15:0] m_axi_T_BUS_WSTRB;
output   m_axi_T_BUS_WLAST;
output  [0:0] m_axi_T_BUS_WID;
output  [0:0] m_axi_T_BUS_WUSER;
output   m_axi_T_BUS_ARVALID;
input   m_axi_T_BUS_ARREADY;
output  [63:0] m_axi_T_BUS_ARADDR;
output  [0:0] m_axi_T_BUS_ARID;
output  [31:0] m_axi_T_BUS_ARLEN;
output  [2:0] m_axi_T_BUS_ARSIZE;
output  [1:0] m_axi_T_BUS_ARBURST;
output  [1:0] m_axi_T_BUS_ARLOCK;
output  [3:0] m_axi_T_BUS_ARCACHE;
output  [2:0] m_axi_T_BUS_ARPROT;
output  [3:0] m_axi_T_BUS_ARQOS;
output  [3:0] m_axi_T_BUS_ARREGION;
output  [0:0] m_axi_T_BUS_ARUSER;
input   m_axi_T_BUS_RVALID;
output   m_axi_T_BUS_RREADY;
input  [127:0] m_axi_T_BUS_RDATA;
input   m_axi_T_BUS_RLAST;
input  [0:0] m_axi_T_BUS_RID;
input  [4:0] m_axi_T_BUS_RFIFONUM;
input  [0:0] m_axi_T_BUS_RUSER;
input  [1:0] m_axi_T_BUS_RRESP;
input   m_axi_T_BUS_BVALID;
output   m_axi_T_BUS_BREADY;
input  [1:0] m_axi_T_BUS_BRESP;
input  [0:0] m_axi_T_BUS_BID;
input  [0:0] m_axi_T_BUS_BUSER;
input  [31:0] add405;
output  [11:0] tt_loc_V_address0;
output   tt_loc_V_ce0;
input  [84:0] tt_loc_V_q0;
input  [63:0] tt;
input  [34:0] zext_ln257;
input  [3:0] trunc_ln14;

reg ap_idle;
reg m_axi_T_BUS_AWVALID;
reg m_axi_T_BUS_WVALID;
reg m_axi_T_BUS_BREADY;
reg tt_loc_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln257_fu_202_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    T_BUS_blk_n_AW;
wire    ap_block_pp0_stage0;
reg    T_BUS_blk_n_W;
reg    T_BUS_blk_n_B;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln258_fu_231_p1;
reg   [0:0] trunc_ln258_reg_677;
reg   [59:0] trunc_ln_reg_682;
wire   [15:0] shl_ln258_fu_622_p2;
reg   [15:0] shl_ln258_reg_687;
wire   [127:0] shl_ln258_1_fu_640_p2;
reg   [127:0] shl_ln258_1_reg_692;
wire   [63:0] i_7_cast82_fu_214_p1;
wire  signed [63:0] sext_ln258_fu_646_p1;
reg    ap_block_pp0_stage0_01001;
reg   [31:0] i_fu_134;
wire   [31:0] add_ln257_fu_208_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_i_7;
wire   [34:0] shl_ln7_fu_219_p3;
wire   [63:0] zext_ln258_2_fu_227_p1;
wire   [63:0] add_ln258_2_fu_235_p2;
wire   [63:0] zext_ln257_cast_fu_190_p1;
wire   [63:0] add_ln258_fu_241_p2;
wire   [0:0] p_Result_16_fu_268_p3;
wire   [84:0] tmp_V_fu_276_p2;
wire   [84:0] tmp_V_4_fu_282_p3;
wire   [63:0] t_fu_290_p4;
reg   [63:0] tmp_s_fu_300_p3;
wire   [20:0] trunc_ln1267_fu_318_p1;
wire   [63:0] p_Result_17_fu_322_p3;
reg   [63:0] tmp_2_fu_330_p3;
wire   [31:0] trunc_ln1269_fu_338_p1;
wire   [31:0] NZeros_fu_308_p1;
wire   [0:0] hitNonZero_fu_312_p2;
wire   [31:0] NZeros_4_fu_342_p2;
wire   [31:0] NZeros_6_fu_348_p3;
wire   [31:0] sub_ln1095_fu_356_p2;
wire   [31:0] lsb_index_fu_362_p2;
wire   [30:0] tmp_fu_368_p4;
wire   [6:0] trunc_ln1098_fu_384_p1;
wire   [6:0] sub_ln1098_fu_388_p2;
wire   [84:0] zext_ln1098_fu_394_p1;
wire   [84:0] lshr_ln1098_fu_398_p2;
wire   [84:0] p_Result_s_fu_404_p2;
wire   [0:0] icmp_ln1097_fu_378_p2;
wire   [0:0] icmp_ln1098_fu_410_p2;
wire   [0:0] tmp_4_fu_422_p3;
wire   [0:0] p_Result_13_fu_436_p3;
wire   [0:0] xor_ln1100_fu_430_p2;
wire   [0:0] and_ln1100_fu_444_p2;
wire   [0:0] a_fu_416_p2;
wire   [0:0] or_ln1100_fu_450_p2;
wire   [31:0] add_ln1105_fu_470_p2;
wire   [84:0] zext_ln1105_fu_476_p1;
wire   [31:0] sub_ln1106_fu_486_p2;
wire   [84:0] zext_ln1106_fu_492_p1;
wire   [84:0] lshr_ln1105_fu_480_p2;
wire   [84:0] shl_ln1106_fu_496_p2;
wire   [0:0] icmp_ln1105_fu_464_p2;
wire   [63:0] trunc_ln1106_fu_502_p1;
wire   [63:0] trunc_ln1106_2_fu_506_p1;
wire   [1:0] or_ln1100_3_fu_456_p3;
wire   [63:0] m_fu_510_p3;
wire   [63:0] zext_ln1112_fu_518_p1;
wire   [63:0] m_5_fu_522_p2;
wire   [62:0] m_8_fu_528_p4;
wire   [0:0] p_Result_14_fu_542_p3;
wire   [10:0] trunc_ln1094_fu_558_p1;
wire   [10:0] sub_ln1116_fu_562_p2;
wire   [10:0] select_ln1094_fu_550_p3;
wire   [10:0] add_ln1122_fu_568_p2;
wire   [63:0] zext_ln1113_fu_538_p1;
wire   [11:0] tmp_3_fu_574_p3;
wire   [0:0] icmp_ln1086_fu_262_p2;
wire   [63:0] p_Result_18_fu_582_p5;
wire   [63:0] select_ln1086_fu_594_p3;
wire   [3:0] trunc_ln258_1_fu_602_p3;
wire   [3:0] add_ln258_1_fu_613_p2;
wire   [15:0] zext_ln258_1_fu_618_p1;
wire   [6:0] shl_ln258_2_fu_628_p3;
wire   [127:0] zext_ln258_fu_609_p1;
wire   [127:0] zext_ln258_3_fu_636_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

runge_kutta_45_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln257_fu_202_p2 == 1'd0))) begin
            i_fu_134 <= add_ln257_fu_208_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_134 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        shl_ln258_1_reg_692 <= shl_ln258_1_fu_640_p2;
        shl_ln258_reg_687 <= shl_ln258_fu_622_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln257_fu_202_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln258_reg_677 <= trunc_ln258_fu_231_p1;
        trunc_ln_reg_682 <= {{add_ln258_fu_241_p2[63:4]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        T_BUS_blk_n_AW = m_axi_T_BUS_AWREADY;
    end else begin
        T_BUS_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        T_BUS_blk_n_B = m_axi_T_BUS_BVALID;
    end else begin
        T_BUS_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        T_BUS_blk_n_W = m_axi_T_BUS_WREADY;
    end else begin
        T_BUS_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln257_fu_202_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_7 = 32'd0;
    end else begin
        ap_sig_allocacmp_i_7 = i_fu_134;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_T_BUS_AWVALID = 1'b1;
    end else begin
        m_axi_T_BUS_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_T_BUS_BREADY = 1'b1;
    end else begin
        m_axi_T_BUS_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_T_BUS_WVALID = 1'b1;
    end else begin
        m_axi_T_BUS_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tt_loc_V_ce0 = 1'b1;
    end else begin
        tt_loc_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign NZeros_4_fu_342_p2 = (trunc_ln1269_fu_338_p1 + NZeros_fu_308_p1);

assign NZeros_6_fu_348_p3 = ((hitNonZero_fu_312_p2[0:0] == 1'b1) ? NZeros_4_fu_342_p2 : NZeros_fu_308_p1);

assign NZeros_fu_308_p1 = tmp_s_fu_300_p3[31:0];

assign a_fu_416_p2 = (icmp_ln1098_fu_410_p2 & icmp_ln1097_fu_378_p2);

assign add_ln1105_fu_470_p2 = ($signed(sub_ln1095_fu_356_p2) + $signed(32'd4294967242));

assign add_ln1122_fu_568_p2 = (sub_ln1116_fu_562_p2 + select_ln1094_fu_550_p3);

assign add_ln257_fu_208_p2 = (ap_sig_allocacmp_i_7 + 32'd1);

assign add_ln258_1_fu_613_p2 = (trunc_ln14 + trunc_ln258_1_fu_602_p3);

assign add_ln258_2_fu_235_p2 = (zext_ln258_2_fu_227_p1 + tt);

assign add_ln258_fu_241_p2 = (add_ln258_2_fu_235_p2 + zext_ln257_cast_fu_190_p1);

assign and_ln1100_fu_444_p2 = (xor_ln1100_fu_430_p2 & p_Result_13_fu_436_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((m_axi_T_BUS_BVALID == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_T_BUS_BVALID == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((m_axi_T_BUS_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((m_axi_T_BUS_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_T_BUS_BVALID == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((m_axi_T_BUS_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((m_axi_T_BUS_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = (m_axi_T_BUS_BVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign hitNonZero_fu_312_p2 = ((t_fu_290_p4 == 64'd0) ? 1'b1 : 1'b0);

assign i_7_cast82_fu_214_p1 = ap_sig_allocacmp_i_7;

assign icmp_ln1086_fu_262_p2 = ((tt_loc_V_q0 == 85'd0) ? 1'b1 : 1'b0);

assign icmp_ln1097_fu_378_p2 = (($signed(tmp_fu_368_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1098_fu_410_p2 = ((p_Result_s_fu_404_p2 != 85'd0) ? 1'b1 : 1'b0);

assign icmp_ln1105_fu_464_p2 = (($signed(lsb_index_fu_362_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_202_p2 = ((ap_sig_allocacmp_i_7 == add405) ? 1'b1 : 1'b0);

assign lsb_index_fu_362_p2 = ($signed(sub_ln1095_fu_356_p2) + $signed(32'd4294967243));

assign lshr_ln1098_fu_398_p2 = 85'd38685626227668133590597631 >> zext_ln1098_fu_394_p1;

assign lshr_ln1105_fu_480_p2 = tmp_V_4_fu_282_p3 >> zext_ln1105_fu_476_p1;

assign m_5_fu_522_p2 = (m_fu_510_p3 + zext_ln1112_fu_518_p1);

assign m_8_fu_528_p4 = {{m_5_fu_522_p2[63:1]}};

assign m_axi_T_BUS_ARADDR = 64'd0;

assign m_axi_T_BUS_ARBURST = 2'd0;

assign m_axi_T_BUS_ARCACHE = 4'd0;

assign m_axi_T_BUS_ARID = 1'd0;

assign m_axi_T_BUS_ARLEN = 32'd0;

assign m_axi_T_BUS_ARLOCK = 2'd0;

assign m_axi_T_BUS_ARPROT = 3'd0;

assign m_axi_T_BUS_ARQOS = 4'd0;

assign m_axi_T_BUS_ARREGION = 4'd0;

assign m_axi_T_BUS_ARSIZE = 3'd0;

assign m_axi_T_BUS_ARUSER = 1'd0;

assign m_axi_T_BUS_ARVALID = 1'b0;

assign m_axi_T_BUS_AWADDR = sext_ln258_fu_646_p1;

assign m_axi_T_BUS_AWBURST = 2'd0;

assign m_axi_T_BUS_AWCACHE = 4'd0;

assign m_axi_T_BUS_AWID = 1'd0;

assign m_axi_T_BUS_AWLEN = 32'd1;

assign m_axi_T_BUS_AWLOCK = 2'd0;

assign m_axi_T_BUS_AWPROT = 3'd0;

assign m_axi_T_BUS_AWQOS = 4'd0;

assign m_axi_T_BUS_AWREGION = 4'd0;

assign m_axi_T_BUS_AWSIZE = 3'd0;

assign m_axi_T_BUS_AWUSER = 1'd0;

assign m_axi_T_BUS_RREADY = 1'b0;

assign m_axi_T_BUS_WDATA = shl_ln258_1_reg_692;

assign m_axi_T_BUS_WID = 1'd0;

assign m_axi_T_BUS_WLAST = 1'b0;

assign m_axi_T_BUS_WSTRB = shl_ln258_reg_687;

assign m_axi_T_BUS_WUSER = 1'd0;

assign m_fu_510_p3 = ((icmp_ln1105_fu_464_p2[0:0] == 1'b1) ? trunc_ln1106_fu_502_p1 : trunc_ln1106_2_fu_506_p1);

assign or_ln1100_3_fu_456_p3 = {{1'd0}, {or_ln1100_fu_450_p2}};

assign or_ln1100_fu_450_p2 = (and_ln1100_fu_444_p2 | a_fu_416_p2);

assign p_Result_13_fu_436_p3 = tmp_V_4_fu_282_p3[lsb_index_fu_362_p2];

assign p_Result_14_fu_542_p3 = m_5_fu_522_p2[32'd54];

assign p_Result_16_fu_268_p3 = tt_loc_V_q0[32'd84];

assign p_Result_17_fu_322_p3 = {{trunc_ln1267_fu_318_p1}, {43'd8796093022207}};

assign p_Result_18_fu_582_p5 = {{tmp_3_fu_574_p3}, {zext_ln1113_fu_538_p1[51:0]}};

assign p_Result_s_fu_404_p2 = (tmp_V_4_fu_282_p3 & lshr_ln1098_fu_398_p2);

assign select_ln1086_fu_594_p3 = ((icmp_ln1086_fu_262_p2[0:0] == 1'b1) ? 64'd0 : p_Result_18_fu_582_p5);

assign select_ln1094_fu_550_p3 = ((p_Result_14_fu_542_p3[0:0] == 1'b1) ? 11'd1023 : 11'd1022);

assign sext_ln258_fu_646_p1 = $signed(trunc_ln_reg_682);

assign shl_ln1106_fu_496_p2 = tmp_V_4_fu_282_p3 << zext_ln1106_fu_492_p1;

assign shl_ln258_1_fu_640_p2 = zext_ln258_fu_609_p1 << zext_ln258_3_fu_636_p1;

assign shl_ln258_2_fu_628_p3 = {{add_ln258_1_fu_613_p2}, {3'd0}};

assign shl_ln258_fu_622_p2 = 16'd255 << zext_ln258_1_fu_618_p1;

assign shl_ln7_fu_219_p3 = {{ap_sig_allocacmp_i_7}, {3'd0}};

assign sub_ln1095_fu_356_p2 = (32'd85 - NZeros_6_fu_348_p3);

assign sub_ln1098_fu_388_p2 = (7'd11 - trunc_ln1098_fu_384_p1);

assign sub_ln1106_fu_486_p2 = (32'd54 - sub_ln1095_fu_356_p2);

assign sub_ln1116_fu_562_p2 = (11'd30 - trunc_ln1094_fu_558_p1);

assign t_fu_290_p4 = {{tmp_V_4_fu_282_p3[84:21]}};

always @ (p_Result_17_fu_322_p3) begin
    if (p_Result_17_fu_322_p3[63] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd0;
    end else if (p_Result_17_fu_322_p3[62] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd1;
    end else if (p_Result_17_fu_322_p3[61] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd2;
    end else if (p_Result_17_fu_322_p3[60] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd3;
    end else if (p_Result_17_fu_322_p3[59] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd4;
    end else if (p_Result_17_fu_322_p3[58] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd5;
    end else if (p_Result_17_fu_322_p3[57] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd6;
    end else if (p_Result_17_fu_322_p3[56] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd7;
    end else if (p_Result_17_fu_322_p3[55] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd8;
    end else if (p_Result_17_fu_322_p3[54] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd9;
    end else if (p_Result_17_fu_322_p3[53] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd10;
    end else if (p_Result_17_fu_322_p3[52] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd11;
    end else if (p_Result_17_fu_322_p3[51] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd12;
    end else if (p_Result_17_fu_322_p3[50] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd13;
    end else if (p_Result_17_fu_322_p3[49] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd14;
    end else if (p_Result_17_fu_322_p3[48] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd15;
    end else if (p_Result_17_fu_322_p3[47] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd16;
    end else if (p_Result_17_fu_322_p3[46] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd17;
    end else if (p_Result_17_fu_322_p3[45] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd18;
    end else if (p_Result_17_fu_322_p3[44] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd19;
    end else if (p_Result_17_fu_322_p3[43] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd20;
    end else if (p_Result_17_fu_322_p3[42] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd21;
    end else if (p_Result_17_fu_322_p3[41] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd22;
    end else if (p_Result_17_fu_322_p3[40] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd23;
    end else if (p_Result_17_fu_322_p3[39] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd24;
    end else if (p_Result_17_fu_322_p3[38] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd25;
    end else if (p_Result_17_fu_322_p3[37] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd26;
    end else if (p_Result_17_fu_322_p3[36] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd27;
    end else if (p_Result_17_fu_322_p3[35] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd28;
    end else if (p_Result_17_fu_322_p3[34] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd29;
    end else if (p_Result_17_fu_322_p3[33] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd30;
    end else if (p_Result_17_fu_322_p3[32] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd31;
    end else if (p_Result_17_fu_322_p3[31] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd32;
    end else if (p_Result_17_fu_322_p3[30] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd33;
    end else if (p_Result_17_fu_322_p3[29] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd34;
    end else if (p_Result_17_fu_322_p3[28] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd35;
    end else if (p_Result_17_fu_322_p3[27] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd36;
    end else if (p_Result_17_fu_322_p3[26] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd37;
    end else if (p_Result_17_fu_322_p3[25] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd38;
    end else if (p_Result_17_fu_322_p3[24] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd39;
    end else if (p_Result_17_fu_322_p3[23] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd40;
    end else if (p_Result_17_fu_322_p3[22] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd41;
    end else if (p_Result_17_fu_322_p3[21] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd42;
    end else if (p_Result_17_fu_322_p3[20] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd43;
    end else if (p_Result_17_fu_322_p3[19] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd44;
    end else if (p_Result_17_fu_322_p3[18] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd45;
    end else if (p_Result_17_fu_322_p3[17] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd46;
    end else if (p_Result_17_fu_322_p3[16] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd47;
    end else if (p_Result_17_fu_322_p3[15] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd48;
    end else if (p_Result_17_fu_322_p3[14] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd49;
    end else if (p_Result_17_fu_322_p3[13] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd50;
    end else if (p_Result_17_fu_322_p3[12] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd51;
    end else if (p_Result_17_fu_322_p3[11] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd52;
    end else if (p_Result_17_fu_322_p3[10] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd53;
    end else if (p_Result_17_fu_322_p3[9] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd54;
    end else if (p_Result_17_fu_322_p3[8] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd55;
    end else if (p_Result_17_fu_322_p3[7] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd56;
    end else if (p_Result_17_fu_322_p3[6] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd57;
    end else if (p_Result_17_fu_322_p3[5] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd58;
    end else if (p_Result_17_fu_322_p3[4] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd59;
    end else if (p_Result_17_fu_322_p3[3] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd60;
    end else if (p_Result_17_fu_322_p3[2] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd61;
    end else if (p_Result_17_fu_322_p3[1] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd62;
    end else if (p_Result_17_fu_322_p3[0] == 1'b1) begin
        tmp_2_fu_330_p3 = 64'd63;
    end else begin
        tmp_2_fu_330_p3 = 64'd64;
    end
end

assign tmp_3_fu_574_p3 = {{p_Result_16_fu_268_p3}, {add_ln1122_fu_568_p2}};

assign tmp_4_fu_422_p3 = lsb_index_fu_362_p2[32'd31];

assign tmp_V_4_fu_282_p3 = ((p_Result_16_fu_268_p3[0:0] == 1'b1) ? tmp_V_fu_276_p2 : tt_loc_V_q0);

assign tmp_V_fu_276_p2 = (85'd0 - tt_loc_V_q0);

assign tmp_fu_368_p4 = {{lsb_index_fu_362_p2[31:1]}};

always @ (t_fu_290_p4) begin
    if (t_fu_290_p4[63] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd0;
    end else if (t_fu_290_p4[62] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd1;
    end else if (t_fu_290_p4[61] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd2;
    end else if (t_fu_290_p4[60] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd3;
    end else if (t_fu_290_p4[59] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd4;
    end else if (t_fu_290_p4[58] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd5;
    end else if (t_fu_290_p4[57] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd6;
    end else if (t_fu_290_p4[56] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd7;
    end else if (t_fu_290_p4[55] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd8;
    end else if (t_fu_290_p4[54] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd9;
    end else if (t_fu_290_p4[53] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd10;
    end else if (t_fu_290_p4[52] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd11;
    end else if (t_fu_290_p4[51] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd12;
    end else if (t_fu_290_p4[50] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd13;
    end else if (t_fu_290_p4[49] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd14;
    end else if (t_fu_290_p4[48] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd15;
    end else if (t_fu_290_p4[47] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd16;
    end else if (t_fu_290_p4[46] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd17;
    end else if (t_fu_290_p4[45] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd18;
    end else if (t_fu_290_p4[44] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd19;
    end else if (t_fu_290_p4[43] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd20;
    end else if (t_fu_290_p4[42] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd21;
    end else if (t_fu_290_p4[41] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd22;
    end else if (t_fu_290_p4[40] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd23;
    end else if (t_fu_290_p4[39] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd24;
    end else if (t_fu_290_p4[38] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd25;
    end else if (t_fu_290_p4[37] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd26;
    end else if (t_fu_290_p4[36] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd27;
    end else if (t_fu_290_p4[35] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd28;
    end else if (t_fu_290_p4[34] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd29;
    end else if (t_fu_290_p4[33] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd30;
    end else if (t_fu_290_p4[32] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd31;
    end else if (t_fu_290_p4[31] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd32;
    end else if (t_fu_290_p4[30] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd33;
    end else if (t_fu_290_p4[29] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd34;
    end else if (t_fu_290_p4[28] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd35;
    end else if (t_fu_290_p4[27] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd36;
    end else if (t_fu_290_p4[26] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd37;
    end else if (t_fu_290_p4[25] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd38;
    end else if (t_fu_290_p4[24] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd39;
    end else if (t_fu_290_p4[23] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd40;
    end else if (t_fu_290_p4[22] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd41;
    end else if (t_fu_290_p4[21] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd42;
    end else if (t_fu_290_p4[20] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd43;
    end else if (t_fu_290_p4[19] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd44;
    end else if (t_fu_290_p4[18] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd45;
    end else if (t_fu_290_p4[17] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd46;
    end else if (t_fu_290_p4[16] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd47;
    end else if (t_fu_290_p4[15] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd48;
    end else if (t_fu_290_p4[14] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd49;
    end else if (t_fu_290_p4[13] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd50;
    end else if (t_fu_290_p4[12] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd51;
    end else if (t_fu_290_p4[11] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd52;
    end else if (t_fu_290_p4[10] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd53;
    end else if (t_fu_290_p4[9] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd54;
    end else if (t_fu_290_p4[8] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd55;
    end else if (t_fu_290_p4[7] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd56;
    end else if (t_fu_290_p4[6] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd57;
    end else if (t_fu_290_p4[5] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd58;
    end else if (t_fu_290_p4[4] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd59;
    end else if (t_fu_290_p4[3] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd60;
    end else if (t_fu_290_p4[2] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd61;
    end else if (t_fu_290_p4[1] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd62;
    end else if (t_fu_290_p4[0] == 1'b1) begin
        tmp_s_fu_300_p3 = 64'd63;
    end else begin
        tmp_s_fu_300_p3 = 64'd64;
    end
end

assign trunc_ln1094_fu_558_p1 = NZeros_6_fu_348_p3[10:0];

assign trunc_ln1098_fu_384_p1 = sub_ln1095_fu_356_p2[6:0];

assign trunc_ln1106_2_fu_506_p1 = shl_ln1106_fu_496_p2[63:0];

assign trunc_ln1106_fu_502_p1 = lshr_ln1105_fu_480_p2[63:0];

assign trunc_ln1267_fu_318_p1 = tmp_V_4_fu_282_p3[20:0];

assign trunc_ln1269_fu_338_p1 = tmp_2_fu_330_p3[31:0];

assign trunc_ln258_1_fu_602_p3 = {{trunc_ln258_reg_677}, {3'd0}};

assign trunc_ln258_fu_231_p1 = ap_sig_allocacmp_i_7[0:0];

assign tt_loc_V_address0 = i_7_cast82_fu_214_p1;

assign xor_ln1100_fu_430_p2 = (tmp_4_fu_422_p3 ^ 1'd1);

assign zext_ln1098_fu_394_p1 = sub_ln1098_fu_388_p2;

assign zext_ln1105_fu_476_p1 = add_ln1105_fu_470_p2;

assign zext_ln1106_fu_492_p1 = sub_ln1106_fu_486_p2;

assign zext_ln1112_fu_518_p1 = or_ln1100_3_fu_456_p3;

assign zext_ln1113_fu_538_p1 = m_8_fu_528_p4;

assign zext_ln257_cast_fu_190_p1 = zext_ln257;

assign zext_ln258_1_fu_618_p1 = add_ln258_1_fu_613_p2;

assign zext_ln258_2_fu_227_p1 = shl_ln7_fu_219_p3;

assign zext_ln258_3_fu_636_p1 = shl_ln258_2_fu_628_p3;

assign zext_ln258_fu_609_p1 = select_ln1086_fu_594_p3;

endmodule //runge_kutta_45_runge_kutta_45_Pipeline_last_axi_write_tt
