// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module runge_kutta_45_macply (
        ap_ready,
        result_V_read,
        x_V_read,
        y_V_read,
        ap_return
);


output   ap_ready;
input  [176:0] result_V_read;
input  [176:0] x_V_read;
input  [176:0] y_V_read;
output  [176:0] ap_return;

wire   [279:0] r_V_fu_44_p2;
wire   [286:0] lhs_fu_50_p3;
wire  signed [286:0] sext_ln859_fu_58_p1;
wire   [286:0] ret_V_fu_62_p2;

runge_kutta_45_mul_177s_177s_280_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 177 ),
    .din1_WIDTH( 177 ),
    .dout_WIDTH( 280 ))
mul_177s_177s_280_1_1_U68(
    .din0(y_V_read),
    .din1(x_V_read),
    .dout(r_V_fu_44_p2)
);

assign ap_ready = 1'b1;

assign ap_return = {{ret_V_fu_62_p2[286:110]}};

assign lhs_fu_50_p3 = {{result_V_read}, {110'd0}};

assign ret_V_fu_62_p2 = ($signed(lhs_fu_50_p3) + $signed(sext_ln859_fu_58_p1));

assign sext_ln859_fu_58_p1 = $signed(r_V_fu_44_p2);

endmodule //runge_kutta_45_macply
