// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module runge_kutta_45_ode_fpga (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        out_offset,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        in_offset,
        c_address0,
        c_ce0,
        c_q0,
        mu
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [84:0] out_r_d0;
input  [63:0] out_offset;
output  [14:0] in_r_address0;
output   in_r_ce0;
input  [84:0] in_r_q0;
input  [63:0] in_offset;
output  [2:0] c_address0;
output   c_ce0;
input  [84:0] c_q0;
input  [84:0] mu;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] out_r_address0;
reg out_r_ce0;
reg out_r_we0;
reg[84:0] out_r_d0;
reg[14:0] in_r_address0;
reg in_r_ce0;
reg[2:0] c_address0;
reg c_ce0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [14:0] empty_79_fu_287_p2;
reg   [14:0] empty_79_reg_725;
reg   [1:0] loop_index29_t_load_reg_731;
wire    ap_CS_fsm_state2;
wire   [1:0] empty_80_fu_311_p2;
reg   [1:0] empty_80_reg_738;
wire   [0:0] exitcond116_fu_305_p2;
reg   [1:0] loop_index26_t_load_reg_773;
wire    ap_CS_fsm_state4;
wire   [1:0] empty_82_fu_364_p2;
reg   [1:0] empty_82_reg_780;
wire   [0:0] exitcond105_fu_358_p2;
reg   [1:0] loop_index23_t_load_reg_815;
wire    ap_CS_fsm_state6;
wire   [1:0] empty_84_fu_428_p2;
reg   [1:0] empty_84_reg_822;
wire   [0:0] exitcond94_fu_422_p2;
reg   [1:0] loop_index20_t_load_reg_857;
wire    ap_CS_fsm_state8;
wire   [1:0] empty_85_fu_471_p2;
reg   [1:0] empty_85_reg_864;
wire   [0:0] exitcond83_fu_465_p2;
reg   [1:0] i_9_reg_917;
wire    ap_CS_fsm_state10;
wire   [31:0] zext_ln95_fu_515_p1;
reg   [31:0] zext_ln95_reg_921;
wire   [1:0] i_10_fu_526_p2;
reg   [1:0] i_10_reg_929;
wire   [0:0] icmp_ln95_fu_520_p2;
wire   [5:0] empty_88_fu_590_p2;
reg   [5:0] empty_88_reg_967;
wire    grp_vel_der_fu_216_ap_start;
wire    grp_vel_der_fu_216_ap_done;
wire    grp_vel_der_fu_216_ap_idle;
wire    grp_vel_der_fu_216_ap_ready;
wire   [84:0] grp_vel_der_fu_216_ap_return;
wire    grp_ode_fpga_Pipeline_1_fu_243_ap_start;
wire    grp_ode_fpga_Pipeline_1_fu_243_ap_done;
wire    grp_ode_fpga_Pipeline_1_fu_243_ap_idle;
wire    grp_ode_fpga_Pipeline_1_fu_243_ap_ready;
wire   [5:0] grp_ode_fpga_Pipeline_1_fu_243_out_r_address0;
wire    grp_ode_fpga_Pipeline_1_fu_243_out_r_ce0;
wire    grp_ode_fpga_Pipeline_1_fu_243_out_r_we0;
wire   [84:0] grp_ode_fpga_Pipeline_1_fu_243_out_r_d0;
wire    grp_ode_fpga_Pipeline_2_fu_253_ap_start;
wire    grp_ode_fpga_Pipeline_2_fu_253_ap_done;
wire    grp_ode_fpga_Pipeline_2_fu_253_ap_idle;
wire    grp_ode_fpga_Pipeline_2_fu_253_ap_ready;
wire   [5:0] grp_ode_fpga_Pipeline_2_fu_253_out_r_address0;
wire    grp_ode_fpga_Pipeline_2_fu_253_out_r_ce0;
wire    grp_ode_fpga_Pipeline_2_fu_253_out_r_we0;
wire   [84:0] grp_ode_fpga_Pipeline_2_fu_253_out_r_d0;
reg    grp_vel_der_fu_216_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_ode_fpga_Pipeline_1_fu_243_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_ode_fpga_Pipeline_2_fu_253_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [63:0] p_cast_fu_322_p1;
wire   [63:0] p_cast11_fu_385_p1;
wire   [63:0] loop_index23_t_cast_fu_417_p1;
wire   [63:0] sum2_cast_fu_483_p1;
reg   [1:0] loop_index29_t_fu_64;
wire    ap_CS_fsm_state3;
reg   [84:0] r_in_V_2_fu_68;
reg   [84:0] r_in_V_2_1_fu_72;
reg   [84:0] r_in_V_2_2_fu_76;
reg   [1:0] loop_index26_t_fu_80;
wire    ap_CS_fsm_state5;
reg   [84:0] v_in_V_2_fu_84;
reg   [84:0] v_in_V_2_1_fu_88;
reg   [84:0] v_in_V_2_2_fu_92;
reg   [1:0] loop_index23_t_fu_96;
wire    ap_CS_fsm_state7;
reg   [84:0] cr_V_2_fu_100;
reg   [84:0] cr_V_2_1_fu_104;
reg   [84:0] cr_V_2_2_fu_108;
reg   [1:0] loop_index20_t_fu_112;
wire    ap_CS_fsm_state9;
reg   [84:0] cv_V_2_fu_116;
reg   [84:0] cv_V_2_1_fu_120;
reg   [84:0] cv_V_2_2_fu_124;
reg   [1:0] i_fu_128;
reg   [84:0] dr_dt_V_2_fu_132;
wire   [84:0] dr_dt_V_0_fu_637_p2;
reg   [84:0] dr_dt_V_2_1_fu_136;
reg   [84:0] dr_dt_V_2_2_fu_140;
reg   [84:0] dv_dt_V_2_fu_144;
reg   [84:0] dv_dt_V_2_1_fu_148;
reg   [84:0] dv_dt_V_2_2_fu_152;
wire   [11:0] empty_fu_263_p1;
wire   [13:0] empty_78_fu_275_p1;
wire   [14:0] p_shl_fu_267_p3;
wire   [14:0] p_shl1_fu_279_p3;
wire   [14:0] loop_index29_t_cast9_fu_301_p1;
wire   [14:0] empty_81_fu_317_p2;
wire   [2:0] loop_index26_cast_fu_354_p1;
wire   [2:0] add_ptr_sum_fu_370_p2;
wire   [14:0] add_ptr_sum_cast10_fu_376_p1;
wire   [14:0] empty_83_fu_380_p2;
wire   [2:0] loop_index20_cast_fu_461_p1;
wire   [2:0] sum2_fu_477_p2;
wire   [2:0] empty_86_fu_568_p1;
wire   [4:0] empty_87_fu_579_p1;
wire   [5:0] p_shl4_fu_571_p3;
wire   [5:0] p_shl5_fu_582_p3;
wire   [84:0] tmp_5_fu_626_p5;
wire   [84:0] tmp_fu_615_p5;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_vel_der_fu_216_ap_start_reg = 1'b0;
#0 grp_ode_fpga_Pipeline_1_fu_243_ap_start_reg = 1'b0;
#0 grp_ode_fpga_Pipeline_2_fu_253_ap_start_reg = 1'b0;
end

runge_kutta_45_vel_der grp_vel_der_fu_216(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_vel_der_fu_216_ap_start),
    .ap_done(grp_vel_der_fu_216_ap_done),
    .ap_idle(grp_vel_der_fu_216_ap_idle),
    .ap_ready(grp_vel_der_fu_216_ap_ready),
    .p_read(r_in_V_2_fu_68),
    .p_read1(r_in_V_2_1_fu_72),
    .p_read2(r_in_V_2_2_fu_76),
    .i_read(zext_ln95_reg_921),
    .mu_V_read(mu),
    .p_read3(cr_V_2_fu_100),
    .p_read4(cr_V_2_1_fu_104),
    .p_read5(cr_V_2_2_fu_108),
    .ap_return(grp_vel_der_fu_216_ap_return)
);

runge_kutta_45_ode_fpga_Pipeline_1 grp_ode_fpga_Pipeline_1_fu_243(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ode_fpga_Pipeline_1_fu_243_ap_start),
    .ap_done(grp_ode_fpga_Pipeline_1_fu_243_ap_done),
    .ap_idle(grp_ode_fpga_Pipeline_1_fu_243_ap_idle),
    .ap_ready(grp_ode_fpga_Pipeline_1_fu_243_ap_ready),
    .dr_dt_V_0_04(dr_dt_V_2_fu_132),
    .dr_dt_V_1_05(dr_dt_V_2_1_fu_136),
    .dr_dt_V_2_06(dr_dt_V_2_2_fu_140),
    .empty(empty_88_reg_967),
    .out_r_address0(grp_ode_fpga_Pipeline_1_fu_243_out_r_address0),
    .out_r_ce0(grp_ode_fpga_Pipeline_1_fu_243_out_r_ce0),
    .out_r_we0(grp_ode_fpga_Pipeline_1_fu_243_out_r_we0),
    .out_r_d0(grp_ode_fpga_Pipeline_1_fu_243_out_r_d0)
);

runge_kutta_45_ode_fpga_Pipeline_2 grp_ode_fpga_Pipeline_2_fu_253(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ode_fpga_Pipeline_2_fu_253_ap_start),
    .ap_done(grp_ode_fpga_Pipeline_2_fu_253_ap_done),
    .ap_idle(grp_ode_fpga_Pipeline_2_fu_253_ap_idle),
    .ap_ready(grp_ode_fpga_Pipeline_2_fu_253_ap_ready),
    .dv_dt_V_0_07(dv_dt_V_2_fu_144),
    .dv_dt_V_1_08(dv_dt_V_2_1_fu_148),
    .dv_dt_V_2_09(dv_dt_V_2_2_fu_152),
    .empty(empty_88_reg_967),
    .out_r_address0(grp_ode_fpga_Pipeline_2_fu_253_out_r_address0),
    .out_r_ce0(grp_ode_fpga_Pipeline_2_fu_253_out_r_ce0),
    .out_r_we0(grp_ode_fpga_Pipeline_2_fu_253_out_r_we0),
    .out_r_d0(grp_ode_fpga_Pipeline_2_fu_253_out_r_d0)
);

runge_kutta_45_mux_32_85_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 85 ),
    .din1_WIDTH( 85 ),
    .din2_WIDTH( 85 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 85 ))
mux_32_85_1_1_U60(
    .din0(v_in_V_2_fu_84),
    .din1(v_in_V_2_1_fu_88),
    .din2(v_in_V_2_2_fu_92),
    .din3(i_fu_128),
    .dout(tmp_fu_615_p5)
);

runge_kutta_45_mux_32_85_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 85 ),
    .din1_WIDTH( 85 ),
    .din2_WIDTH( 85 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 85 ))
mux_32_85_1_1_U61(
    .din0(cv_V_2_fu_116),
    .din1(cv_V_2_1_fu_120),
    .din2(cv_V_2_2_fu_124),
    .din3(i_fu_128),
    .dout(tmp_5_fu_626_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ode_fpga_Pipeline_1_fu_243_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln95_fu_520_p2 == 1'd1))) begin
            grp_ode_fpga_Pipeline_1_fu_243_ap_start_reg <= 1'b1;
        end else if ((grp_ode_fpga_Pipeline_1_fu_243_ap_ready == 1'b1)) begin
            grp_ode_fpga_Pipeline_1_fu_243_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ode_fpga_Pipeline_2_fu_253_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_ode_fpga_Pipeline_2_fu_253_ap_start_reg <= 1'b1;
        end else if ((grp_ode_fpga_Pipeline_2_fu_253_ap_ready == 1'b1)) begin
            grp_ode_fpga_Pipeline_2_fu_253_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_vel_der_fu_216_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln95_fu_520_p2 == 1'd0))) begin
            grp_vel_der_fu_216_ap_start_reg <= 1'b1;
        end else if ((grp_vel_der_fu_216_ap_ready == 1'b1)) begin
            grp_vel_der_fu_216_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (exitcond83_fu_465_p2 == 1'd1))) begin
        i_fu_128 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state11) & (grp_vel_der_fu_216_ap_done == 1'b1))) begin
        i_fu_128 <= i_10_reg_929;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (exitcond94_fu_422_p2 == 1'd1))) begin
        loop_index20_t_fu_112 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        loop_index20_t_fu_112 <= empty_85_reg_864;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond105_fu_358_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        loop_index23_t_fu_96 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        loop_index23_t_fu_96 <= empty_84_reg_822;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond116_fu_305_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        loop_index26_t_fu_80 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        loop_index26_t_fu_80 <= empty_82_reg_780;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        loop_index29_t_fu_64 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        loop_index29_t_fu_64 <= empty_80_reg_738;
    end
end

always @ (posedge ap_clk) begin
    if (((loop_index23_t_load_reg_815 == 2'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        cr_V_2_1_fu_104 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(loop_index23_t_load_reg_815 == 2'd1) & ~(loop_index23_t_load_reg_815 == 2'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        cr_V_2_2_fu_108 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((loop_index23_t_load_reg_815 == 2'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        cr_V_2_fu_100 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (loop_index20_t_load_reg_857 == 2'd1))) begin
        cv_V_2_1_fu_120 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(loop_index20_t_load_reg_857 == 2'd1) & ~(loop_index20_t_load_reg_857 == 2'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        cv_V_2_2_fu_124 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (loop_index20_t_load_reg_857 == 2'd0))) begin
        cv_V_2_fu_116 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (grp_vel_der_fu_216_ap_done == 1'b1) & (i_9_reg_917 == 2'd1))) begin
        dr_dt_V_2_1_fu_136 <= dr_dt_V_0_fu_637_p2;
        dv_dt_V_2_1_fu_148 <= grp_vel_der_fu_216_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_9_reg_917 == 2'd1) & ~(i_9_reg_917 == 2'd0) & (1'b1 == ap_CS_fsm_state11) & (grp_vel_der_fu_216_ap_done == 1'b1))) begin
        dr_dt_V_2_2_fu_140 <= dr_dt_V_0_fu_637_p2;
        dv_dt_V_2_2_fu_152 <= grp_vel_der_fu_216_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (grp_vel_der_fu_216_ap_done == 1'b1) & (i_9_reg_917 == 2'd0))) begin
        dr_dt_V_2_fu_132 <= dr_dt_V_0_fu_637_p2;
        dv_dt_V_2_fu_144 <= grp_vel_der_fu_216_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_79_reg_725[14 : 1] <= empty_79_fu_287_p2[14 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_80_reg_738 <= empty_80_fu_311_p2;
        loop_index29_t_load_reg_731 <= loop_index29_t_fu_64;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_82_reg_780 <= empty_82_fu_364_p2;
        loop_index26_t_load_reg_773 <= loop_index26_t_fu_80;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        empty_84_reg_822 <= empty_84_fu_428_p2;
        loop_index23_t_load_reg_815 <= loop_index23_t_fu_96;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        empty_85_reg_864 <= empty_85_fu_471_p2;
        loop_index20_t_load_reg_857 <= loop_index20_t_fu_112;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln95_fu_520_p2 == 1'd1))) begin
        empty_88_reg_967[5 : 1] <= empty_88_fu_590_p2[5 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_10_reg_929 <= i_10_fu_526_p2;
        i_9_reg_917 <= i_fu_128;
        zext_ln95_reg_921[1 : 0] <= zext_ln95_fu_515_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((loop_index29_t_load_reg_731 == 2'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        r_in_V_2_1_fu_72 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(loop_index29_t_load_reg_731 == 2'd1) & ~(loop_index29_t_load_reg_731 == 2'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        r_in_V_2_2_fu_76 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((loop_index29_t_load_reg_731 == 2'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        r_in_V_2_fu_68 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((loop_index26_t_load_reg_773 == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        v_in_V_2_1_fu_88 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(loop_index26_t_load_reg_773 == 2'd1) & ~(loop_index26_t_load_reg_773 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        v_in_V_2_2_fu_92 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((loop_index26_t_load_reg_773 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        v_in_V_2_fu_84 <= in_r_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_vel_der_fu_216_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_ode_fpga_Pipeline_1_fu_243_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_ode_fpga_Pipeline_2_fu_253_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state14) & (grp_ode_fpga_Pipeline_2_fu_253_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (grp_ode_fpga_Pipeline_2_fu_253_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        c_address0 = sum2_cast_fu_483_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        c_address0 = loop_index23_t_cast_fu_417_p1;
    end else begin
        c_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_r_address0 = p_cast11_fu_385_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_r_address0 = p_cast_fu_322_p1;
    end else begin
        in_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        in_r_ce0 = 1'b1;
    end else begin
        in_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        out_r_address0 = grp_ode_fpga_Pipeline_2_fu_253_out_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        out_r_address0 = grp_ode_fpga_Pipeline_1_fu_243_out_r_address0;
    end else begin
        out_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        out_r_ce0 = grp_ode_fpga_Pipeline_2_fu_253_out_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        out_r_ce0 = grp_ode_fpga_Pipeline_1_fu_243_out_r_ce0;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        out_r_d0 = grp_ode_fpga_Pipeline_2_fu_253_out_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        out_r_d0 = grp_ode_fpga_Pipeline_1_fu_243_out_r_d0;
    end else begin
        out_r_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        out_r_we0 = grp_ode_fpga_Pipeline_2_fu_253_out_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        out_r_we0 = grp_ode_fpga_Pipeline_1_fu_243_out_r_we0;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond116_fu_305_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond105_fu_358_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (exitcond94_fu_422_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (exitcond83_fu_465_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln95_fu_520_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_vel_der_fu_216_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_ode_fpga_Pipeline_1_fu_243_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (grp_ode_fpga_Pipeline_2_fu_253_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ptr_sum_cast10_fu_376_p1 = add_ptr_sum_fu_370_p2;

assign add_ptr_sum_fu_370_p2 = (loop_index26_cast_fu_354_p1 + 3'd3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign dr_dt_V_0_fu_637_p2 = (tmp_5_fu_626_p5 + tmp_fu_615_p5);

assign empty_78_fu_275_p1 = in_offset[13:0];

assign empty_79_fu_287_p2 = (p_shl_fu_267_p3 - p_shl1_fu_279_p3);

assign empty_80_fu_311_p2 = (loop_index29_t_fu_64 + 2'd1);

assign empty_81_fu_317_p2 = (empty_79_reg_725 + loop_index29_t_cast9_fu_301_p1);

assign empty_82_fu_364_p2 = (loop_index26_t_fu_80 + 2'd1);

assign empty_83_fu_380_p2 = (empty_79_reg_725 + add_ptr_sum_cast10_fu_376_p1);

assign empty_84_fu_428_p2 = (loop_index23_t_fu_96 + 2'd1);

assign empty_85_fu_471_p2 = (loop_index20_t_fu_112 + 2'd1);

assign empty_86_fu_568_p1 = out_offset[2:0];

assign empty_87_fu_579_p1 = out_offset[4:0];

assign empty_88_fu_590_p2 = (p_shl4_fu_571_p3 - p_shl5_fu_582_p3);

assign empty_fu_263_p1 = in_offset[11:0];

assign exitcond105_fu_358_p2 = ((loop_index26_t_fu_80 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond116_fu_305_p2 = ((loop_index29_t_fu_64 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond83_fu_465_p2 = ((loop_index20_t_fu_112 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond94_fu_422_p2 = ((loop_index23_t_fu_96 == 2'd3) ? 1'b1 : 1'b0);

assign grp_ode_fpga_Pipeline_1_fu_243_ap_start = grp_ode_fpga_Pipeline_1_fu_243_ap_start_reg;

assign grp_ode_fpga_Pipeline_2_fu_253_ap_start = grp_ode_fpga_Pipeline_2_fu_253_ap_start_reg;

assign grp_vel_der_fu_216_ap_start = grp_vel_der_fu_216_ap_start_reg;

assign i_10_fu_526_p2 = (i_fu_128 + 2'd1);

assign icmp_ln95_fu_520_p2 = ((i_fu_128 == 2'd3) ? 1'b1 : 1'b0);

assign loop_index20_cast_fu_461_p1 = loop_index20_t_fu_112;

assign loop_index23_t_cast_fu_417_p1 = loop_index23_t_fu_96;

assign loop_index26_cast_fu_354_p1 = loop_index26_t_fu_80;

assign loop_index29_t_cast9_fu_301_p1 = loop_index29_t_fu_64;

assign p_cast11_fu_385_p1 = empty_83_fu_380_p2;

assign p_cast_fu_322_p1 = empty_81_fu_317_p2;

assign p_shl1_fu_279_p3 = {{empty_78_fu_275_p1}, {1'd0}};

assign p_shl4_fu_571_p3 = {{empty_86_fu_568_p1}, {3'd0}};

assign p_shl5_fu_582_p3 = {{empty_87_fu_579_p1}, {1'd0}};

assign p_shl_fu_267_p3 = {{empty_fu_263_p1}, {3'd0}};

assign sum2_cast_fu_483_p1 = sum2_fu_477_p2;

assign sum2_fu_477_p2 = (loop_index20_cast_fu_461_p1 + 3'd3);

assign zext_ln95_fu_515_p1 = i_fu_128;

always @ (posedge ap_clk) begin
    empty_79_reg_725[0] <= 1'b0;
    zext_ln95_reg_921[31:2] <= 30'b000000000000000000000000000000;
    empty_88_reg_967[0] <= 1'b0;
end

endmodule //runge_kutta_45_ode_fpga
